import hrd.views.cms
import hrd.views.codes
import hrd.views.user
import hrd.views.organisation
import hrd.views.resource
import hrd.views.general
import hrd.views.menu
import hrd.views.translation
import hrd.views.news
